export const FETCH_STORY_ID = "FETCH_STORY_ID";
export const FETCH_STORY_DETAIL = "FETCH_STORY_DETAIL";
export const LOAD_STORY_LIST_ID = "LOAD_STORY_LIST_ID";
export const LOAD_STORY_DETAIL = "LOAD_STORY_DETAIL";
export const UPDATE_STORE_FULL_STORY_DATA = "UPDATE_STORE_FULL_STORY_DATA";
export const STORY_DATA_AFTER_DELETE = "STORY_DATA_AFTER_DELETE";
export const API_LIMIT = 90;
