export const FETCH_STORY_ID = "FETCH_STORY_ID";
export const FETCH_STORY_DETAIL = "FETCH_STORY_DETAIL";
export const LOAD_STORY_LIST_ID = "LOAD_STORY_LIST_ID";
export const LOAD_STORY_DETAIL = "LOAD_STORY_DETAIL";
